# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c388128130dbd2bc9939853d0a0048c64813b0e1665ac33850fb2ea92924292264a7787850a856fef63826c09b6285f6580873ed9b2a9013701de1465eb775f2

test:
  secret_key_base: b4f3bda53cd9de84e74af752e108877cfd8187ebf20bde9e092fecae2cb5ffa7049b5fd380d9af7d863459b2956bc45305cc0b0aa2ab8546ab5aaabb14894abd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
